[project]
name = "hydronet"
version = "0.1.0"
description = "HEROSLAB"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "sqlalchemy>=2.0.36",
]
