// This file is auto-generated by @hey-api/openapi-ts

export const Body_download_data_api_download__postSchema = {
    properties: {
        dataType: {
            '$ref': '#/components/schemas/DataType'
        },
        period: {
            '$ref': '#/components/schemas/Period'
        },
        stations: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Stations'
        }
    },
    type: 'object',
    required: ['dataType', 'period', 'stations'],
    title: 'Body_download_data_api_download__post'
} as const;

export const CredentialInfoSchema = {
    properties: {
        service_name: {
            type: 'string',
            title: 'Service Name'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        last_updated: {
            type: 'string',
            format: 'date-time',
            title: 'Last Updated'
        },
        updated_by: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated By'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        }
    },
    type: 'object',
    required: ['service_name', 'username', 'last_updated', 'is_active'],
    title: 'CredentialInfo',
    description: 'Response body for credential information.'
} as const;

export const CredentialUpdateSchema = {
    properties: {
        service_name: {
            type: 'string',
            title: 'Service Name',
            description: "Name of the service (e.g., 'engtec')"
        },
        username: {
            type: 'string',
            title: 'Username',
            description: 'New username for the service'
        },
        password: {
            type: 'string',
            title: 'Password',
            description: 'New password for the service'
        }
    },
    type: 'object',
    required: ['service_name', 'username', 'password'],
    title: 'CredentialUpdate',
    description: 'Request body for updating credentials.'
} as const;

export const CredentialUpdateResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        service_name: {
            type: 'string',
            title: 'Service Name'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        updated_by: {
            type: 'string',
            title: 'Updated By'
        }
    },
    type: 'object',
    required: ['success', 'message', 'service_name', 'updated_at', 'updated_by'],
    title: 'CredentialUpdateResponse',
    description: 'Response body after successful credential update.'
} as const;

export const DataTypeSchema = {
    type: 'string',
    enum: ['weather', 'linigrafo', 'gauge'],
    title: 'DataType'
} as const;

export const GaugeDataSchema = {
    properties: {
        time: {
            type: 'string',
            format: 'date-time',
            title: 'Time'
        },
        data: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data'
        }
    },
    type: 'object',
    required: ['time', 'data'],
    title: 'GaugeData',
    description: 'Gauge Data in the db.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HealthCheckResponseSchema = {
    properties: {
        status: {
            type: 'string',
            enum: ['healthy', 'degraded', 'unhealthy'],
            title: 'Status'
        },
        database: {
            type: 'string',
            enum: ['healthy', 'unhealthy'],
            title: 'Database'
        },
        services: {
            items: {
                '$ref': '#/components/schemas/ServiceStatus'
            },
            type: 'array',
            title: 'Services'
        },
        message: {
            type: 'string',
            title: 'Message',
            default: ''
        }
    },
    type: 'object',
    required: ['status', 'database', 'services'],
    title: 'HealthCheckResponse',
    description: 'Overall health check response.'
} as const;

export const IntervalSchema = {
    type: 'string',
    enum: ['hourly', 'daily'],
    title: 'Interval'
} as const;

export const LinigrafoAvgDataSchema = {
    properties: {
        date: {
            type: 'string',
            format: 'date-time',
            title: 'Date'
        },
        avg_height: {
            type: 'number',
            title: 'Avg Height'
        }
    },
    type: 'object',
    required: ['date', 'avg_height'],
    title: 'LinigrafoAvgData',
    description: 'Avg Sensor in the db.'
} as const;

export const LinigrafoDataSchema = {
    properties: {
        data_leitura: {
            type: 'string',
            format: 'date-time',
            title: 'Data Leitura'
        },
        mac: {
            type: 'string',
            title: 'Mac'
        },
        local: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Local'
        },
        valor_leitura: {
            type: 'number',
            title: 'Valor Leitura'
        }
    },
    type: 'object',
    required: ['data_leitura', 'mac', 'local', 'valor_leitura'],
    title: 'LinigrafoData',
    description: 'Sensor in the db.'
} as const;

export const LinigrafoLastUpdateSchema = {
    properties: {
        mac: {
            type: 'string',
            title: 'Mac'
        },
        data: {
            type: 'string',
            format: 'date-time',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['mac', 'data'],
    title: 'LinigrafoLastUpdate',
    description: 'Sensor in the db.'
} as const;

export const LocationSchema = {
    properties: {
        alias: {
            type: 'string',
            title: 'Alias'
        },
        sensor: {
            '$ref': '#/components/schemas/SensorType'
        },
        status: {
            '$ref': '#/components/schemas/SensorStatus'
        },
        latitude: {
            type: 'number',
            title: 'Latitude'
        },
        longitude: {
            type: 'number',
            title: 'Longitude'
        }
    },
    type: 'object',
    required: ['alias', 'sensor', 'status', 'latitude', 'longitude'],
    title: 'Location'
} as const;

export const LocationDataSchema = {
    properties: {
        nome: {
            type: 'string',
            title: 'Nome'
        },
        latitude: {
            type: 'number',
            title: 'Latitude'
        },
        longitude: {
            type: 'number',
            title: 'Longitude'
        }
    },
    type: 'object',
    required: ['nome', 'latitude', 'longitude'],
    title: 'LocationData'
} as const;

export const MetereologicoDataSchema = {
    properties: {
        data: {
            type: 'string',
            format: 'date-time',
            title: 'Data'
        },
        pressao_atmosferica: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pressao Atmosferica'
        },
        temperatura: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Temperatura'
        },
        umidade_ar: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Umidade Ar'
        },
        precipitacao: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Precipitacao'
        },
        velocidade_vento: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Velocidade Vento'
        },
        direcao_vento: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Direcao Vento'
        },
        bateria: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bateria'
        }
    },
    type: 'object',
    required: ['data', 'pressao_atmosferica', 'temperatura', 'umidade_ar', 'precipitacao', 'velocidade_vento', 'direcao_vento', 'bateria'],
    title: 'MetereologicoData'
} as const;

export const PeriodSchema = {
    properties: {
        begin: {
            type: 'string',
            format: 'date-time',
            title: 'Begin'
        },
        end: {
            type: 'string',
            format: 'date-time',
            title: 'End'
        }
    },
    type: 'object',
    required: ['begin', 'end'],
    title: 'Period'
} as const;

export const SensorStatusSchema = {
    type: 'string',
    enum: ['ok', 'missing', 'faulty', 'no_signal', 'maintenance', 'error', 'unknown'],
    title: 'SensorStatus'
} as const;

export const SensorTypeSchema = {
    type: 'string',
    enum: ['linigrafo', 'weather', 'gauge'],
    title: 'SensorType'
} as const;

export const ServiceStatusSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        status: {
            type: 'string',
            enum: ['healthy', 'unhealthy', 'unknown'],
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message',
            default: ''
        }
    },
    type: 'object',
    required: ['name', 'status'],
    title: 'ServiceStatus',
    description: 'Status of an external service.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;