// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
} from '@hey-api/client-fetch'
import {
  type GetDataApiLinigrafosGetData,
  type GetDataApiLinigrafosGetError,
  type GetDataApiLinigrafosGetResponse,
  type UpdateDataApiLinigrafosUpdateGetError,
  type UpdateDataApiLinigrafosUpdateGetResponse,
  type LastUpdateApiLinigrafosUpdateLastGetError,
  type LastUpdateApiLinigrafosUpdateLastGetResponse,
  type SensorsLastupdateApiLinigrafosLastupdateGetError,
  type SensorsLastupdateApiLinigrafosLastupdateGetResponse,
  type GetLocalAvgDataApiLinigrafosAvgLocalIntervalGetData,
  type GetLocalAvgDataApiLinigrafosAvgLocalIntervalGetError,
  type GetLocalAvgDataApiLinigrafosAvgLocalIntervalGetResponse,
  type GetLocalDataApiLinigrafosLocalGetData,
  type GetLocalDataApiLinigrafosLocalGetError,
  type GetLocalDataApiLinigrafosLocalGetResponse,
  type GetDataApiMetereologicoGetData,
  type GetDataApiMetereologicoGetError,
  type GetDataApiMetereologicoGetResponse,
  type UpdateDataApiMetereologicoUpdateGetError,
  type UpdateDataApiMetereologicoUpdateGetResponse,
  type LastUpdateApiMetereologicoUpdateLastGetError,
  type LastUpdateApiMetereologicoUpdateLastGetResponse,
  type CanLoginApiMetereologicoCanLoginGetError,
  type CanLoginApiMetereologicoCanLoginGetResponse,
  type GetDataDaysApiMetereologicoDaysGetError,
  type GetDataDaysApiMetereologicoDaysGetResponse,
  type GetLocationsv2ApiLocationV2GetError,
  type GetLocationsv2ApiLocationV2GetResponse,
  type GetLocationsApiLocationGetError,
  type GetLocationsApiLocationGetResponse,
  type DownloadDataApiDownloadPostData,
  type DownloadDataApiDownloadPostError,
  type DownloadDataApiDownloadPostResponse,
  type GetStationDataApiGaugesStationGetData,
  type GetStationDataApiGaugesStationGetError,
  type GetStationDataApiGaugesStationGetResponse,
  type GetDailyStationDataApiGaugesDailyStationGetData,
  type GetDailyStationDataApiGaugesDailyStationGetError,
  type GetDailyStationDataApiGaugesDailyStationGetResponse,
  type GetCredentialInfoApiCredentialsInfoServiceNameGetData,
  type GetCredentialInfoApiCredentialsInfoServiceNameGetError,
  type GetCredentialInfoApiCredentialsInfoServiceNameGetResponse,
  type ListServicesApiCredentialsServicesGetError,
  type ListServicesApiCredentialsServicesGetResponse,
  type UpdateCredentialApiCredentialsUpdatePostData,
  type UpdateCredentialApiCredentialsUpdatePostError,
  type UpdateCredentialApiCredentialsUpdatePostResponse,
  type GetCredentialAuditLogApiCredentialsAuditServiceNameGetData,
  type GetCredentialAuditLogApiCredentialsAuditServiceNameGetError,
  type GetCredentialAuditLogApiCredentialsAuditServiceNameGetResponse,
  type HealthCheckApiHealthGetError,
  type HealthCheckApiHealthGetResponse,
  type HealtyApiHealtyGetError,
  type HealtyApiHealtyGetResponse,
  GetDataApiLinigrafosGetResponseTransformer,
  SensorsLastupdateApiLinigrafosLastupdateGetResponseTransformer,
  GetLocalAvgDataApiLinigrafosAvgLocalIntervalGetResponseTransformer,
  GetLocalDataApiLinigrafosLocalGetResponseTransformer,
  GetDataApiMetereologicoGetResponseTransformer,
  GetStationDataApiGaugesStationGetResponseTransformer,
  GetDailyStationDataApiGaugesDailyStationGetResponseTransformer,
  GetCredentialInfoApiCredentialsInfoServiceNameGetResponseTransformer,
  UpdateCredentialApiCredentialsUpdatePostResponseTransformer,
} from './types.gen'

export const client = createClient(createConfig())

/**
 * Get Data
 */
export const getDataApiLinigrafosGet = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<GetDataApiLinigrafosGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetDataApiLinigrafosGetResponse,
    GetDataApiLinigrafosGetError,
    ThrowOnError
  >({
    ...options,
    url: '/api/linigrafos/',
    responseTransformer: GetDataApiLinigrafosGetResponseTransformer,
  })
}

/**
 * Update Data
 */
export const updateDataApiLinigrafosUpdateGet = <
  ThrowOnError extends boolean = false,
>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    UpdateDataApiLinigrafosUpdateGetResponse,
    UpdateDataApiLinigrafosUpdateGetError,
    ThrowOnError
  >({
    ...options,
    url: '/api/linigrafos/update',
  })
}

/**
 * Last Update
 */
export const lastUpdateApiLinigrafosUpdateLastGet = <
  ThrowOnError extends boolean = false,
>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    LastUpdateApiLinigrafosUpdateLastGetResponse,
    LastUpdateApiLinigrafosUpdateLastGetError,
    ThrowOnError
  >({
    ...options,
    url: '/api/linigrafos/update/last',
  })
}

/**
 * Sensors Lastupdate
 */
export const sensorsLastupdateApiLinigrafosLastupdateGet = <
  ThrowOnError extends boolean = false,
>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    SensorsLastupdateApiLinigrafosLastupdateGetResponse,
    SensorsLastupdateApiLinigrafosLastupdateGetError,
    ThrowOnError
  >({
    ...options,
    url: '/api/linigrafos/lastupdate',
    responseTransformer:
      SensorsLastupdateApiLinigrafosLastupdateGetResponseTransformer,
  })
}

/**
 * Get Local Avg Data
 */
export const getLocalAvgDataApiLinigrafosAvgLocalIntervalGet = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    GetLocalAvgDataApiLinigrafosAvgLocalIntervalGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    GetLocalAvgDataApiLinigrafosAvgLocalIntervalGetResponse,
    GetLocalAvgDataApiLinigrafosAvgLocalIntervalGetError,
    ThrowOnError
  >({
    ...options,
    url: '/api/linigrafos/avg/{local}/{interval}',
    responseTransformer:
      GetLocalAvgDataApiLinigrafosAvgLocalIntervalGetResponseTransformer,
  })
}

/**
 * Get Local Data
 */
export const getLocalDataApiLinigrafosLocalGet = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    GetLocalDataApiLinigrafosLocalGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    GetLocalDataApiLinigrafosLocalGetResponse,
    GetLocalDataApiLinigrafosLocalGetError,
    ThrowOnError
  >({
    ...options,
    url: '/api/linigrafos/{local}',
    responseTransformer: GetLocalDataApiLinigrafosLocalGetResponseTransformer,
  })
}

/**
 * Get Data
 */
export const getDataApiMetereologicoGet = <
  ThrowOnError extends boolean = false,
>(
  options?: OptionsLegacyParser<GetDataApiMetereologicoGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetDataApiMetereologicoGetResponse,
    GetDataApiMetereologicoGetError,
    ThrowOnError
  >({
    ...options,
    url: '/api/metereologico/',
    responseTransformer: GetDataApiMetereologicoGetResponseTransformer,
  })
}

/**
 * Update Data
 */
export const updateDataApiMetereologicoUpdateGet = <
  ThrowOnError extends boolean = false,
>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    UpdateDataApiMetereologicoUpdateGetResponse,
    UpdateDataApiMetereologicoUpdateGetError,
    ThrowOnError
  >({
    ...options,
    url: '/api/metereologico/update',
  })
}

/**
 * Last Update
 */
export const lastUpdateApiMetereologicoUpdateLastGet = <
  ThrowOnError extends boolean = false,
>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    LastUpdateApiMetereologicoUpdateLastGetResponse,
    LastUpdateApiMetereologicoUpdateLastGetError,
    ThrowOnError
  >({
    ...options,
    url: '/api/metereologico/update/last',
  })
}

/**
 * Can Login
 */
export const canLoginApiMetereologicoCanLoginGet = <
  ThrowOnError extends boolean = false,
>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    CanLoginApiMetereologicoCanLoginGetResponse,
    CanLoginApiMetereologicoCanLoginGetError,
    ThrowOnError
  >({
    ...options,
    url: '/api/metereologico/can_login',
  })
}

/**
 * Get Data Days
 */
export const getDataDaysApiMetereologicoDaysGet = <
  ThrowOnError extends boolean = false,
>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetDataDaysApiMetereologicoDaysGetResponse,
    GetDataDaysApiMetereologicoDaysGetError,
    ThrowOnError
  >({
    ...options,
    url: '/api/metereologico/days',
  })
}

/**
 * Get Locationsv2
 */
export const getLocationsv2ApiLocationV2Get = <
  ThrowOnError extends boolean = false,
>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetLocationsv2ApiLocationV2GetResponse,
    GetLocationsv2ApiLocationV2GetError,
    ThrowOnError
  >({
    ...options,
    url: '/api/location/v2',
  })
}

/**
 * Get Locations
 */
export const getLocationsApiLocationGet = <
  ThrowOnError extends boolean = false,
>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetLocationsApiLocationGetResponse,
    GetLocationsApiLocationGetError,
    ThrowOnError
  >({
    ...options,
    url: '/api/location/',
  })
}

/**
 * Download Data
 */
export const downloadDataApiDownloadPost = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<DownloadDataApiDownloadPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    DownloadDataApiDownloadPostResponse,
    DownloadDataApiDownloadPostError,
    ThrowOnError
  >({
    ...options,
    url: '/api/download/',
  })
}

/**
 * Get Station Data
 */
export const getStationDataApiGaugesStationGet = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    GetStationDataApiGaugesStationGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    GetStationDataApiGaugesStationGetResponse,
    GetStationDataApiGaugesStationGetError,
    ThrowOnError
  >({
    ...options,
    url: '/api/gauges/{station}',
    responseTransformer: GetStationDataApiGaugesStationGetResponseTransformer,
  })
}

/**
 * Get Daily Station Data
 */
export const getDailyStationDataApiGaugesDailyStationGet = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    GetDailyStationDataApiGaugesDailyStationGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    GetDailyStationDataApiGaugesDailyStationGetResponse,
    GetDailyStationDataApiGaugesDailyStationGetError,
    ThrowOnError
  >({
    ...options,
    url: '/api/gauges/daily/{station}',
    responseTransformer:
      GetDailyStationDataApiGaugesDailyStationGetResponseTransformer,
  })
}

/**
 * Get Credential Info
 * Get information about a service's credentials (without the password).
 *
 * Args:
 * service_name: Name of the service (e.g., 'engtec')
 *
 * Returns:
 * Credential metadata including last update time
 */
export const getCredentialInfoApiCredentialsInfoServiceNameGet = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    GetCredentialInfoApiCredentialsInfoServiceNameGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    GetCredentialInfoApiCredentialsInfoServiceNameGetResponse,
    GetCredentialInfoApiCredentialsInfoServiceNameGetError,
    ThrowOnError
  >({
    ...options,
    url: '/api/credentials/info/{service_name}',
    responseTransformer:
      GetCredentialInfoApiCredentialsInfoServiceNameGetResponseTransformer,
  })
}

/**
 * List Services
 * List all configured services and their credential status.
 *
 * Returns:
 * Dictionary with list of services and their metadata
 */
export const listServicesApiCredentialsServicesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ListServicesApiCredentialsServicesGetResponse,
    ListServicesApiCredentialsServicesGetError,
    ThrowOnError
  >({
    ...options,
    url: '/api/credentials/services',
  })
}

/**
 * Update Credential
 * Update API credentials for a service.
 *
 * The new credentials will be encrypted before storage and the application's
 * credential cache will be refreshed to use the new credentials on the next request.
 *
 * Args:
 * credential_update: Object containing service_name, username, and password
 *
 * Returns:
 * Success response with update timestamp
 *
 * Raises:
 * HTTPException: If service not found or update fails
 */
export const updateCredentialApiCredentialsUpdatePost = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    UpdateCredentialApiCredentialsUpdatePostData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).post<
    UpdateCredentialApiCredentialsUpdatePostResponse,
    UpdateCredentialApiCredentialsUpdatePostError,
    ThrowOnError
  >({
    ...options,
    url: '/api/credentials/update',
    responseTransformer:
      UpdateCredentialApiCredentialsUpdatePostResponseTransformer,
  })
}

/**
 * Get Credential Audit Log
 * Retrieve the audit log for a service's credential changes.
 *
 * Args:
 * service_name: Name of the service
 * limit: Maximum number of audit records to return (default: 10)
 *
 * Returns:
 * Dictionary with audit log entries
 */
export const getCredentialAuditLogApiCredentialsAuditServiceNameGet = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    GetCredentialAuditLogApiCredentialsAuditServiceNameGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    GetCredentialAuditLogApiCredentialsAuditServiceNameGetResponse,
    GetCredentialAuditLogApiCredentialsAuditServiceNameGetError,
    ThrowOnError
  >({
    ...options,
    url: '/api/credentials/audit/{service_name}',
  })
}

/**
 * Health Check
 * Comprehensive health check endpoint.
 *
 * Returns:
 * HealthCheckResponse: Overall health status with database and external services status
 */
export const healthCheckApiHealthGet = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    HealthCheckApiHealthGetResponse,
    HealthCheckApiHealthGetError,
    ThrowOnError
  >({
    ...options,
    url: '/api/health',
  })
}

/**
 * @deprecated
 * Healty
 * Deprecated: Use /health instead.
 */
export const healtyApiHealtyGet = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    HealtyApiHealtyGetResponse,
    HealtyApiHealtyGetError,
    ThrowOnError
  >({
    ...options,
    url: '/api/healty',
  })
}
