// This file is auto-generated by @hey-api/openapi-ts

export type Body_download_data_api_download__post = {
    dataType: DataType;
    period: Period;
    stations: Array<(string)>;
};

/**
 * Response body for credential information.
 */
export type CredentialInfo = {
    service_name: string;
    username: string;
    last_updated: Date;
    updated_by?: (string | null);
    is_active: boolean;
};

/**
 * Request body for updating credentials.
 */
export type CredentialUpdate = {
    /**
     * Name of the service (e.g., 'engtec')
     */
    service_name: string;
    /**
     * New username for the service
     */
    username: string;
    /**
     * New password for the service
     */
    password: string;
};

/**
 * Response body after successful credential update.
 */
export type CredentialUpdateResponse = {
    success: boolean;
    message: string;
    service_name: string;
    updated_at: Date;
    updated_by: string;
};

export type DataType = 'weather' | 'linigrafo' | 'gauge';

export const DataType = {
    WEATHER: 'weather',
    LINIGRAFO: 'linigrafo',
    GAUGE: 'gauge'
} as const;

/**
 * Gauge Data in the db.
 */
export type GaugeData = {
    time: Date;
    data: (number | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Interval = 'hourly' | 'daily';

export const Interval = {
    HOURLY: 'hourly',
    DAILY: 'daily'
} as const;

/**
 * Avg Sensor in the db.
 */
export type LinigrafoAvgData = {
    date: Date;
    avg_height: number;
};

/**
 * Sensor in the db.
 */
export type LinigrafoData = {
    data_leitura: Date;
    mac: string;
    local: (string | null);
    valor_leitura: number;
};

/**
 * Sensor in the db.
 */
export type LinigrafoLastUpdate = {
    mac: string;
    data: Date;
};

export type Location = {
    alias: string;
    sensor: SensorType;
    status: SensorStatus;
    latitude: number;
    longitude: number;
};

export type LocationData = {
    nome: string;
    latitude: number;
    longitude: number;
};

export type MetereologicoData = {
    data: Date;
    pressao_atmosferica: (number | null);
    temperatura: (number | null);
    umidade_ar: (number | null);
    precipitacao: (number | null);
    velocidade_vento: (number | null);
    direcao_vento: (number | null);
    bateria: (number | null);
};

export type Period = {
    begin: Date;
    end: Date;
};

export type SensorStatus = 'ok' | 'missing' | 'faulty' | 'no_signal' | 'maintenance' | 'error' | 'unknown';

export const SensorStatus = {
    OK: 'ok',
    MISSING: 'missing',
    FAULTY: 'faulty',
    NO_SIGNAL: 'no_signal',
    MAINTENANCE: 'maintenance',
    ERROR: 'error',
    UNKNOWN: 'unknown'
} as const;

export type SensorType = 'linigrafo' | 'weather' | 'gauge';

export const SensorType = {
    LINIGRAFO: 'linigrafo',
    WEATHER: 'weather',
    GAUGE: 'gauge'
} as const;

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type GetDataApiLinigrafosGetData = {
    query?: {
        end?: (Date | null);
        start?: (Date | null);
    };
};

export type GetDataApiLinigrafosGetResponse = (Array<LinigrafoData>);

export type GetDataApiLinigrafosGetError = (HTTPValidationError);

export type UpdateDataApiLinigrafosUpdateGetResponse = (unknown);

export type UpdateDataApiLinigrafosUpdateGetError = unknown;

export type LastUpdateApiLinigrafosUpdateLastGetResponse = ((Date | null));

export type LastUpdateApiLinigrafosUpdateLastGetError = unknown;

export type SensorsLastupdateApiLinigrafosLastupdateGetResponse = (Array<LinigrafoLastUpdate>);

export type SensorsLastupdateApiLinigrafosLastupdateGetError = unknown;

export type GetLocalAvgDataApiLinigrafosAvgLocalIntervalGetData = {
    path: {
        interval: Interval;
        local: string;
    };
    query?: {
        daysago?: number;
    };
};

export type GetLocalAvgDataApiLinigrafosAvgLocalIntervalGetResponse = (Array<LinigrafoAvgData>);

export type GetLocalAvgDataApiLinigrafosAvgLocalIntervalGetError = (HTTPValidationError);

export type GetLocalDataApiLinigrafosLocalGetData = {
    path: {
        local: string;
    };
    query?: {
        end?: (Date | null);
        start?: (Date | null);
    };
};

export type GetLocalDataApiLinigrafosLocalGetResponse = (Array<LinigrafoData>);

export type GetLocalDataApiLinigrafosLocalGetError = (HTTPValidationError);

export type GetDataApiMetereologicoGetData = {
    query?: {
        end?: (Date | null);
        start?: (Date | null);
    };
};

export type GetDataApiMetereologicoGetResponse = (Array<MetereologicoData>);

export type GetDataApiMetereologicoGetError = (HTTPValidationError);

export type UpdateDataApiMetereologicoUpdateGetResponse = (unknown);

export type UpdateDataApiMetereologicoUpdateGetError = unknown;

export type LastUpdateApiMetereologicoUpdateLastGetResponse = ((Date | null));

export type LastUpdateApiMetereologicoUpdateLastGetError = unknown;

export type CanLoginApiMetereologicoCanLoginGetResponse = (boolean);

export type CanLoginApiMetereologicoCanLoginGetError = unknown;

export type GetDataDaysApiMetereologicoDaysGetResponse = (Array<(Date)>);

export type GetDataDaysApiMetereologicoDaysGetError = unknown;

export type GetLocationsv2ApiLocationV2GetResponse = (Array<Location>);

export type GetLocationsv2ApiLocationV2GetError = unknown;

export type GetLocationsApiLocationGetResponse = (Array<LocationData>);

export type GetLocationsApiLocationGetError = unknown;

export type DownloadDataApiDownloadPostData = {
    body: Body_download_data_api_download__post;
};

export type DownloadDataApiDownloadPostResponse = (unknown);

export type DownloadDataApiDownloadPostError = (HTTPValidationError);

export type GetStationDataApiGaugesStationGetData = {
    path: {
        station: string;
    };
    query?: {
        end?: (Date | null);
        start?: (Date | null);
    };
};

export type GetStationDataApiGaugesStationGetResponse = (Array<GaugeData>);

export type GetStationDataApiGaugesStationGetError = (HTTPValidationError);

export type GetDailyStationDataApiGaugesDailyStationGetData = {
    path: {
        station: string;
    };
    query?: {
        end?: (Date | null);
        start?: (Date | null);
    };
};

export type GetDailyStationDataApiGaugesDailyStationGetResponse = (Array<GaugeData>);

export type GetDailyStationDataApiGaugesDailyStationGetError = (HTTPValidationError);

export type GetCredentialInfoApiCredentialsInfoServiceNameGetData = {
    path: {
        service_name: string;
    };
};

export type GetCredentialInfoApiCredentialsInfoServiceNameGetResponse = (CredentialInfo);

export type GetCredentialInfoApiCredentialsInfoServiceNameGetError = (HTTPValidationError);

export type ListServicesApiCredentialsServicesGetResponse = ({
    [key: string]: unknown;
});

export type ListServicesApiCredentialsServicesGetError = unknown;

export type UpdateCredentialApiCredentialsUpdatePostData = {
    body: CredentialUpdate;
};

export type UpdateCredentialApiCredentialsUpdatePostResponse = (CredentialUpdateResponse);

export type UpdateCredentialApiCredentialsUpdatePostError = (HTTPValidationError);

export type GetCredentialAuditLogApiCredentialsAuditServiceNameGetData = {
    path: {
        service_name: string;
    };
    query?: {
        limit?: number;
    };
};

export type GetCredentialAuditLogApiCredentialsAuditServiceNameGetResponse = ({
    [key: string]: unknown;
});

export type GetCredentialAuditLogApiCredentialsAuditServiceNameGetError = (HTTPValidationError);

export type HealtyApiHealtyGetResponse = (unknown);

export type HealtyApiHealtyGetError = unknown;

export type GetDataApiLinigrafosGetResponseTransformer = (data: any) => Promise<GetDataApiLinigrafosGetResponse>;

export type LinigrafoDataModelResponseTransformer = (data: any) => LinigrafoData;

export const LinigrafoDataModelResponseTransformer: LinigrafoDataModelResponseTransformer = data => {
    if (data?.data_leitura) {
        data.data_leitura = new Date(data.data_leitura);
    }
    return data;
};

export const GetDataApiLinigrafosGetResponseTransformer: GetDataApiLinigrafosGetResponseTransformer = async (data) => {
    if (Array.isArray(data)) {
        data.forEach(LinigrafoDataModelResponseTransformer);
    }
    return data;
};

export type SensorsLastupdateApiLinigrafosLastupdateGetResponseTransformer = (data: any) => Promise<SensorsLastupdateApiLinigrafosLastupdateGetResponse>;

export type LinigrafoLastUpdateModelResponseTransformer = (data: any) => LinigrafoLastUpdate;

export const LinigrafoLastUpdateModelResponseTransformer: LinigrafoLastUpdateModelResponseTransformer = data => {
    if (data?.data) {
        data.data = new Date(data.data);
    }
    return data;
};

export const SensorsLastupdateApiLinigrafosLastupdateGetResponseTransformer: SensorsLastupdateApiLinigrafosLastupdateGetResponseTransformer = async (data) => {
    if (Array.isArray(data)) {
        data.forEach(LinigrafoLastUpdateModelResponseTransformer);
    }
    return data;
};

export type GetLocalAvgDataApiLinigrafosAvgLocalIntervalGetResponseTransformer = (data: any) => Promise<GetLocalAvgDataApiLinigrafosAvgLocalIntervalGetResponse>;

export type LinigrafoAvgDataModelResponseTransformer = (data: any) => LinigrafoAvgData;

export const LinigrafoAvgDataModelResponseTransformer: LinigrafoAvgDataModelResponseTransformer = data => {
    if (data?.date) {
        data.date = new Date(data.date);
    }
    return data;
};

export const GetLocalAvgDataApiLinigrafosAvgLocalIntervalGetResponseTransformer: GetLocalAvgDataApiLinigrafosAvgLocalIntervalGetResponseTransformer = async (data) => {
    if (Array.isArray(data)) {
        data.forEach(LinigrafoAvgDataModelResponseTransformer);
    }
    return data;
};

export type GetLocalDataApiLinigrafosLocalGetResponseTransformer = (data: any) => Promise<GetLocalDataApiLinigrafosLocalGetResponse>;

export const GetLocalDataApiLinigrafosLocalGetResponseTransformer: GetLocalDataApiLinigrafosLocalGetResponseTransformer = async (data) => {
    if (Array.isArray(data)) {
        data.forEach(LinigrafoDataModelResponseTransformer);
    }
    return data;
};

export type GetDataApiMetereologicoGetResponseTransformer = (data: any) => Promise<GetDataApiMetereologicoGetResponse>;

export type MetereologicoDataModelResponseTransformer = (data: any) => MetereologicoData;

export const MetereologicoDataModelResponseTransformer: MetereologicoDataModelResponseTransformer = data => {
    if (data?.data) {
        data.data = new Date(data.data);
    }
    return data;
};

export const GetDataApiMetereologicoGetResponseTransformer: GetDataApiMetereologicoGetResponseTransformer = async (data) => {
    if (Array.isArray(data)) {
        data.forEach(MetereologicoDataModelResponseTransformer);
    }
    return data;
};

export type GetStationDataApiGaugesStationGetResponseTransformer = (data: any) => Promise<GetStationDataApiGaugesStationGetResponse>;

export type GaugeDataModelResponseTransformer = (data: any) => GaugeData;

export const GaugeDataModelResponseTransformer: GaugeDataModelResponseTransformer = data => {
    if (data?.time) {
        data.time = new Date(data.time);
    }
    return data;
};

export const GetStationDataApiGaugesStationGetResponseTransformer: GetStationDataApiGaugesStationGetResponseTransformer = async (data) => {
    if (Array.isArray(data)) {
        data.forEach(GaugeDataModelResponseTransformer);
    }
    return data;
};

export type GetDailyStationDataApiGaugesDailyStationGetResponseTransformer = (data: any) => Promise<GetDailyStationDataApiGaugesDailyStationGetResponse>;

export const GetDailyStationDataApiGaugesDailyStationGetResponseTransformer: GetDailyStationDataApiGaugesDailyStationGetResponseTransformer = async (data) => {
    if (Array.isArray(data)) {
        data.forEach(GaugeDataModelResponseTransformer);
    }
    return data;
};

export type GetCredentialInfoApiCredentialsInfoServiceNameGetResponseTransformer = (data: any) => Promise<GetCredentialInfoApiCredentialsInfoServiceNameGetResponse>;

export type CredentialInfoModelResponseTransformer = (data: any) => CredentialInfo;

export const CredentialInfoModelResponseTransformer: CredentialInfoModelResponseTransformer = data => {
    if (data?.last_updated) {
        data.last_updated = new Date(data.last_updated);
    }
    return data;
};

export const GetCredentialInfoApiCredentialsInfoServiceNameGetResponseTransformer: GetCredentialInfoApiCredentialsInfoServiceNameGetResponseTransformer = async (data) => {
    CredentialInfoModelResponseTransformer(data);
    return data;
};

export type UpdateCredentialApiCredentialsUpdatePostResponseTransformer = (data: any) => Promise<UpdateCredentialApiCredentialsUpdatePostResponse>;

export type CredentialUpdateResponseModelResponseTransformer = (data: any) => CredentialUpdateResponse;

export const CredentialUpdateResponseModelResponseTransformer: CredentialUpdateResponseModelResponseTransformer = data => {
    if (data?.updated_at) {
        data.updated_at = new Date(data.updated_at);
    }
    return data;
};

export const UpdateCredentialApiCredentialsUpdatePostResponseTransformer: UpdateCredentialApiCredentialsUpdatePostResponseTransformer = async (data) => {
    CredentialUpdateResponseModelResponseTransformer(data);
    return data;
};